openapi: 3.0.0
paths:
  /v1/appointments:
    get:
      tags:
        - Appointments
      summary: Lister les rendez-vous de l'utilisateur
      description: |
        Récupère la liste des rendez-vous de l'utilisateur connecté (patient ou médecin).
        Liste complète avec pagination uniquement, triée par date de rendez-vous descendante.
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: Numéro de la page
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Nombre de résultats par page (max 50)
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
      responses:
        '200':
          description: Rendez-vous récupérés avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Rendez-vous récupérés avec succès"
                  data:
                    $ref: '#/components/schemas/ListeRendezVousResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Profil utilisateur non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: "PROFILE_NOT_FOUND"
                message: "Profil patient non trouvé"
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    ListeRendezVousResponse:
      type: object
      properties:
        rendezVous:
          type: array
          items:
            $ref: '#/components/schemas/RendezVousListeItem'
        pagination:
          $ref: '#/components/schemas/Pagination'
        statistiques:
          $ref: '#/components/schemas/StatistiquesRendezVous'
        user:
          type: object
          properties:
            role:
              type: string
              example: "PATIENT"
            nom:
              type: string
              example: "DIABATE"
            prenom:
              type: string
              example: "Aminata"

    RendezVousListeItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "456e7890-e89b-12d3-a456-426614174000"
        dateRendezVous:
          type: string
          format: date
          description: Date du rendez-vous
          example: "2024-02-15"
        heureDebut:
          type: string
          pattern: "^([0-1][0-9]|2[0-3]):[0-5][0-9]$"
          description: Heure de début
          example: "10:00"
        heureFin:
          type: string
          pattern: "^([0-1][0-9]|2[0-3]):[0-5][0-9]$"
          description: Heure de fin
          example: "10:30"
        typeConsultation:
          type: string
          example: "CLINIQUE"
        statut:
          type: string
          example: "CONFIRME"
        motifConsultation:
          type: string
          example: "Contrôle de routine pour hypertension artérielle"
        niveauUrgence:
          type: string
          example: "NORMAL"
        tarif:
          type: number
          format: decimal
          description: Tarif de la consultation
          example: 25000
        adresseConsultation:
          type: string
          example: "123 Avenue de la République, Plateau"
        symptomes:
          type: string
          nullable: true
          description: Symptômes ou informations complémentaires
          example: "Patient sous traitement depuis 2 ans"
        estPasse:
          type: boolean
          example: false
        estProche:
          type: boolean
          example: true
        dansXMinutes:
          type: integer
          nullable: true
          example: 120
        dateHumaine:
          type: string
          example: "jeudi 15 février 2024"
        heureHumaine:
          type: string
          example: "10:00"
        dateCreation:
          type: string
          format: date-time
        partenaire:
          oneOf:
            - $ref: '#/components/schemas/PartenairePatient'
            - $ref: '#/components/schemas/PartenaireMedecin'
        evaluation:
          type: object
          properties:
            aEvalue:
              type: boolean
              example: false
            details:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  note:
                    type: integer
                    minimum: 1
                    maximum: 5
                  commentaire:
                    type: string
                  typeEvaluation:
                    type: string
                  date:
                    type: string
                    format: date-time
        consultation:
          type: object
          nullable: true
          properties:
            id:
              type: string
              format: uuid
            aDiagnostic:
              type: boolean
            aDocuments:
              type: integer
        actionsPossibles:
          type: array
          description: |
            Actions possibles selon le statut et le rôle:
            - DEMANDE: ANNULER (tous), ACCEPTER/REFUSER (médecin)
            - EN_ATTENTE: ANNULER, REPROGRAMMER (tous)
            - CONFIRME: ANNULER, REPROGRAMMER (tous), COMMENCER_CONSULTATION (médecin si proche)
            - TERMINE: EVALUER (si pas encore évalué)
          items:
            type: string
            enum: [ACCEPTER, REFUSER, ANNULER, REPROGRAMMER, EVALUER, COMMENCER_CONSULTATION]
          example: ["ANNULER", "REPROGRAMMER"]

    PartenairePatient:
      type: object
      properties:
        type:
          type: string
          example: "patient"
        id:
          type: string
          format: uuid
        nom:
          type: string
          example: "DIABATE"
        prenom:
          type: string
          example: "Aminata"
        telephone:
          type: string
          example: "0709876543"
        email:
          type: string
          format: email
        age:
          type: integer
          nullable: true
          example: 35
        sexe:
          type: string
          example: "F"
        groupeSanguin:
          type: string
          nullable: true
          example: "O+"

    PartenaireMedecin:
      type: object
      properties:
        type:
          type: string
          example: "medecin"
        id:
          type: string
          format: uuid
        nom:
          type: string
          example: "KOUAME"
        prenom:
          type: string
          example: "Jean-Baptiste"
        specialites:
          type: array
          items:
            type: string
          description: Liste des spécialités du médecin
          example: ["CARDIOLOGIE", "MEDECINE_GENERALE"]
          nullable: true
        telephone:
          type: string
          example: "0708123456"
        email:
          type: string
          format: email

    StatistiquesRendezVous:
      type: object
      properties:
        total:
          type: integer
          example: 15
        parStatut:
          type: object
          properties:
            DEMANDE:
              type: integer
              example: 1
            EN_ATTENTE:
              type: integer
              example: 0
            CONFIRME:
              type: integer
              example: 3
            REFUSE:
              type: integer
              example: 1
            ANNULE:
              type: integer
              example: 2
            TERMINE:
              type: integer
              example: 8
        prochainRendezVous:
          type: object
          nullable: true
          properties:
            id:
              type: string
              format: uuid
            date:
              type: string
              example: "jeudi 15 février 2024"
            heure:
              type: string
              example: "10:00"
            avec:
              type: string
              example: "Jean-Baptiste KOUAME"
            type:
              type: string
              example: "CLINIQUE"
            dansXMinutes:
              type: integer
              example: 120
        rendezVousEnCours:
          type: integer
          example: 0
        rendezVousAujourdHui:
          type: integer
          example: 1