openapi: 3.0.0
paths:
  /v1/doctors/recommend:
    post:
      tags:
        - Doctors
      summary: Recommandation intelligente de médecins
      description: |
        Système de recommandation intelligent qui analyse les préférences du patient
        (position, spécialité, type de consultation, budget) et propose les 3 meilleurs
        médecins avec un système de scoring avancé. Le premier choix est mis en avant
        avec une explication des raisons de la recommandation.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - latitude
                - longitude
                - typeConsultation
              properties:
                latitude:
                  type: number
                  format: float
                  minimum: -90
                  maximum: 90
                  description: Latitude de la position du patient
                  example: 5.3597
                longitude:
                  type: number
                  format: float
                  minimum: -180
                  maximum: 180
                  description: Longitude de la position du patient
                  example: -4.0083
                adresse:
                  type: string
                  maxLength: 500
                  description: Adresse du patient (optionnel, pour contexte)
                  example: "Cocody, Abidjan"
                specialite:
                  type: string
                  maxLength: 100
                  description: Spécialité médicale recherchée (optionnel)
                  example: "CARDIOLOGIE"
                typeConsultation:
                  type: string
                  enum: [DOMICILE, CLINIQUE, TELECONSULTATION]
                  description: Type de consultation souhaité
                  example: "CLINIQUE"
                budget:
                  type: number
                  minimum: 0
                  maximum: 1000000
                  description: Budget maximum en XOF (optionnel)
                  example: 50000
      responses:
        '200':
          description: Recommandations générées avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Recommandations générées avec succès"
                  data:
                    type: object
                    properties:
                      recommendations:
                        type: array
                        maxItems: 3
                        items:
                          $ref: '#/components/schemas/RecommandationMedecin'
                      criteres:
                        type: object
                        properties:
                          position:
                            type: object
                            properties:
                              latitude:
                                type: number
                              longitude:
                                type: number
                          adresse:
                            type: string
                            nullable: true
                          specialite:
                            type: string
                            nullable: true
                          typeConsultation:
                            type: string
                          budget:
                            type: number
                            nullable: true
                      statistiques:
                        type: object
                        properties:
                          nombreMedecinsAnalyses:
                            type: integer
                            description: Nombre total de médecins analysés
                          scoreMoyenTop3:
                            type: number
                            description: Score moyen des 3 recommandations
                          tarifMoyenEstime:
                            type: integer
                            description: Tarif moyen estimé des recommandations
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

  /v1/doctors/search:
    get:
      tags:
        - Doctors
      summary: Recherche multicritères de médecins (ancienne version)
      description: |
        Recherche avancée de médecins validés avec filtres multiples.
        Permet de trouver des médecins selon la spécialité, localisation, tarifs, services proposés, etc.
        Note: Cette version est maintenue pour compatibilité. Utilisez /doctors/recommend pour une expérience optimisée.
      security:
        - bearerAuth: []
      parameters:
        - name: specialite
          in: query
          description: Spécialité médicale recherchée
          schema:
            type: string
            example: "cardiologie"
        - name: ville
          in: query
          description: Ville de consultation
          schema:
            type: string
            example: "Abidjan"
        - name: disponible
          in: query
          description: Filtrer uniquement les médecins disponibles
          schema:
            type: boolean
            example: true
        - name: tarifMin
          in: query
          description: Tarif minimum de consultation (XOF)
          schema:
            type: number
            minimum: 0
            example: 10000
        - name: tarifMax
          in: query
          description: Tarif maximum de consultation (XOF)
          schema:
            type: number
            minimum: 0
            example: 50000
        - name: noteMin
          in: query
          description: Note minimum (1-5)
          schema:
            type: number
            minimum: 1
            maximum: 5
            example: 4
        - name: domicile
          in: query
          description: Propose des consultations à domicile
          schema:
            type: boolean
            example: true
        - name: teleconsultation
          in: query
          description: Propose des téléconsultations
          schema:
            type: boolean
            example: true
        - name: page
          in: query
          description: Numéro de la page
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Nombre de résultats par page (max 50)
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
        - name: sortBy
          in: query
          description: Champ de tri
          schema:
            type: string
            enum: [note, nom, tarif, experience]
            default: note
        - name: sortOrder
          in: query
          description: Ordre de tri
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: Recherche effectuée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Recherche effectuée avec succès"
                  data:
                    type: object
                    properties:
                      medecins:
                        type: array
                        items:
                          $ref: '#/components/schemas/MedecinRecherche'
                      pagination:
                        $ref: '#/components/schemas/Pagination'
                      filters:
                        type: object
                        properties:
                          specialite:
                            type: string
                            nullable: true
                          ville:
                            type: string
                            nullable: true
                          tarifMin:
                            type: number
                            nullable: true
                          tarifMax:
                            type: number
                            nullable: true
                          noteMin:
                            type: number
                            nullable: true
                          domicile:
                            type: boolean
                          teleconsultation:
                            type: boolean
                          sortBy:
                            type: string
                          sortOrder:
                            type: string
                      statistics:
                        type: object
                        properties:
                          totalMedecinsDisponibles:
                            type: integer
                          medecinAvecDomicile:
                            type: integer
                          medecinAvecTeleconsultation:
                            type: integer
                          noteMoyenneMoyenne:
                            type: number
                            nullable: true
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    MedecinRecherche:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        user:
          type: object
          properties:
            id:
              type: string
              format: uuid
            nom:
              type: string
              example: "KOUAME"
            prenom:
              type: string
              example: "Jean-Baptiste"
            email:
              type: string
              format: email
              example: "jb.kouame@email.com"
            telephone:
              type: string
              example: "0708123456"
        specialitePrincipale:
          type: string
          example: "Cardiologie"
        specialitesSecondaires:
          type: array
          items:
            type: string
          example: ["Médecine interne", "Échographie cardiaque"]
        experienceAnnees:
          type: integer
          example: 15
        noteMoyenne:
          type: number
          format: float
          example: 4.2
          nullable: true
        nombreEvaluations:
          type: integer
          example: 127
        consultations:
          type: object
          properties:
            clinique:
              type: object
              properties:
                disponible:
                  type: boolean
                  example: true
                tarif:
                  type: number
                  example: 25000
                adresse:
                  type: string
                  example: "123 Avenue de la République"
                ville:
                  type: string
                  example: "Abidjan"
            domicile:
              type: object
              properties:
                disponible:
                  type: boolean
                  example: true
                tarif:
                  type: number
                  example: 35000
                rayonKm:
                  type: integer
                  example: 15
            teleconsultation:
              type: object
              properties:
                disponible:
                  type: boolean
                  example: true
                tarif:
                  type: number
                  example: 20000
        disponible:
          type: boolean
          example: true
        prochainCreneauDisponible:
          type: string
          format: date-time
          nullable: true
        numeroOrdre:
          type: string
          example: "CI-MED-12345"
        biographie:
          type: string
          example: "Cardiologue expérimenté spécialisé dans les pathologies cardiovasculaires..."
        languessParlees:
          type: array
          items:
            type: string
          example: ["Français", "Anglais", "Baoulé"]
        certifie:
          type: boolean
          example: true
        photoProfile:
          type: object
          nullable: true
          properties:
            fileId:
              type: string
              example: "medecin_photo_123456789"
            nom_fichier:
              type: string
              example: "photo-profil-5-1704461422123-profile.jpg"
            taille:
              type: integer
              example: 524288
            mime_type:
              type: string
              example: "image/jpeg"
            upload_date:
              type: string
              format: date-time
              example: "2024-01-15T14:30:22.123Z"
            url:
              type: string
              example: "http://localhost:3000/files/uploads/photos/profil/photo-profil-5-1704461422123-profile.jpg"
              description: "URL publique pour accéder à la photo de profil"
        photoCabinet:
          type: object
          nullable: true
          properties:
            fileId:
              type: string
              example: "cabinet_photo_123456789"
            nom_fichier:
              type: string
              example: "photo-cabinet-5-1704461422123-cabinet.jpg"
            taille:
              type: integer
              example: 724288
            mime_type:
              type: string
              example: "image/jpeg"
            upload_date:
              type: string
              format: date-time
              example: "2024-01-15T14:30:22.123Z"
            url:
              type: string
              example: "http://localhost:3000/files/uploads/photos/cabinet/photo-cabinet-5-1704461422123-cabinet.jpg"
              description: "URL publique pour accéder à la photo du cabinet"
  
    RecommandationMedecin:
      type: object
      properties:
        medecin:
          type: object
          properties:
            id:
              type: string
              format: uuid
              example: "123e4567-e89b-12d3-a456-426614174000"
            user:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                nom:
                  type: string
                  example: "KOUAME"
                prenom:
                  type: string
                  example: "Jean-Baptiste"
                email:
                  type: string
                  format: email
                  example: "jb.kouame@email.com"
                telephone:
                  type: string
                  example: "0708123456"
            specialites:
              type: array
              items:
                type: string
              example: ["CARDIOLOGIE", "MEDECINE_INTERNE"]
            experienceAnnees:
              type: integer
              example: 15
              nullable: true
            noteMoyenne:
              type: number
              format: float
              example: 4.2
            nombreEvaluations:
              type: integer
              example: 127
            photoProfile:
              type: object
              nullable: true
              properties:
                fileId:
                  type: string
                nom_fichier:
                  type: string
                url:
                  type: string
            bio:
              type: string
              nullable: true
              example: "Cardiologue expérimenté avec 15 ans d'expérience..."
            languesParlees:
              type: array
              items:
                type: string
              example: ["Français", "Anglais", "Baoulé"]
            clinique:
              type: object
              nullable: true
              properties:
                nom:
                  type: string
                  example: "Clinique de la Paix"
                adresse:
                  type: string
                  example: "123 Avenue de la République"
                ville:
                  type: string
                  example: "Abidjan"
                latitude:
                  type: number
                  format: decimal
                longitude:
                  type: number
                  format: decimal
        score:
          type: number
          format: float
          example: 8.7
          description: Score de recommandation sur 10
        distance:
          type: string
          nullable: true
          example: "2.1 km"
          description: Distance calculée depuis la position du patient
        tarifEstime:
          type: number
          example: 25000
          description: Tarif estimé pour le type de consultation demandé
        disponible:
          type: boolean
          example: true
          description: Indique si le médecin a des créneaux disponibles
        prochainCreneauEstime:
          type: string
          example: "Aujourd'hui ou demain"
          description: Estimation du prochain créneau disponible
        highlighted:
          type: boolean
          example: true
          description: Indique si cette recommandation est mise en avant
        raisonMiseEnAvant:
          type: string
          nullable: true
          example: "Excellentes évaluations patients • Très proche de votre position"
          description: Explication de pourquoi cette recommandation est mise en avant
        scoreDetails:
          type: object
          description: Détail des scores par critère pour transparence
          properties:
            distance:
              type: number
              example: 9.1
              description: Score distance (0-10)
            note:
              type: number
              example: 8.4
              description: Score basé sur les évaluations (0-10)
            experience:
              type: number
              example: 7.5
              description: Score basé sur l'expérience (0-10)
            disponibilite:
              type: number
              example: 10
              description: Score disponibilité (0 ou 10)
            budget:
              type: number
              example: 10
              description: Score compatibilité budget (0-10)
            specialite:
              type: number
              example: 10
              description: Score correspondance spécialité (5 neutre, 10 exact)