openapi: 3.0.0
info:
  title: Admin Doctors Certifications Upload API
  description: Upload des certifications de médecins par les administrateurs
  version: 1.0.0

paths:
  /v1/admin/doctors/{medecinId}/certifications/upload:
    post:
      tags:
        - Administration
      summary: Upload d'une certification de médecin
      description: |
        Permet aux administrateurs d'uploader une certification pour un médecin en attente de validation.
        
        **Types de certifications :**
        - 📜 **Ordre des Médecins** : Certificat d'inscription à l'ordre
        - 🎓 **Formation Continue** : Attestations de formation
        - 🏥 **Spécialisations** : Certificats de spécialité médicale
        - 📋 **Autres** : Documents professionnels validés
        
        **Fonctionnalités :**
        - 📤 **Upload sécurisé** via service de fichiers externe
        - 📋 **Support multi-certifications** : Ajoute sans écraser les existantes
        - 🏷️ **Catégorisation** : Type de certification pour organisation
        - 🔒 **Validation stricte** : Médecin EN_ATTENTE uniquement
        - 📊 **Traçabilité complète** : Admin, IP, horodatage
        - 📁 **Formats acceptés** : PDF, JPG, PNG (max 10MB)
        
        **Workflow :**
        1. Admin sélectionne un médecin en attente
        2. Upload la certification via cette route
        3. Fichier stocké dans le service externe
        4. Métadonnées ajoutées au tableau JSON existant
        
        **User Stories :** Administrateurs-US1 (Gestion comptes médecins)

      security:
        - bearerAuth: []
      
      parameters:
        - name: medecinId
          in: path
          description: ID unique du médecin
          required: true
          schema:
            type: string
            format: uuid
            example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"

      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - certification
              properties:
                certification:
                  type: string
                  format: binary
                  description: |
                    Fichier certification à uploader
                    
                    **Formats acceptés :** PDF, JPG, PNG
                    
                    **Taille max :** 10MB
                description:
                  type: string
                  maxLength: 255
                  description: Description optionnelle de la certification
                  example: "Certificat d'inscription à l'Ordre des Médecins de Côte d'Ivoire"
                type_certification:
                  type: string
                  maxLength: 100
                  description: |
                    Type/catégorie de la certification pour organisation
                    
                    **Exemples suggérés :**
                    - ORDRE_MEDECINS
                    - FORMATION_CONTINUE
                    - SPECIALISATION
                    - ATTESTATION_PROFESSIONNELLE
                  example: "ORDRE_MEDECINS"
            examples:
              ordre_medecins:
                summary: Certificat Ordre des Médecins
                value:
                  certification: "[FICHIER_PDF]"
                  description: "Certificat d'inscription à l'Ordre des Médecins CI"
                  type_certification: "ORDRE_MEDECINS"
              formation_continue:
                summary: Attestation formation continue
                value:
                  certification: "[FICHIER_PDF]"
                  description: "Attestation formation continue 2024"
                  type_certification: "FORMATION_CONTINUE"
              specialisation:
                summary: Certificat de spécialisation
                value:
                  certification: "[FICHIER_PDF]"
                  description: "Certificat de spécialisation en Pédiatrie"
                  type_certification: "SPECIALISATION"

      responses:
        '200':
          description: Certification uploadée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Certification uploadée avec succès"
                  data:
                    type: object
                    properties:
                      medecin:
                        type: object
                        properties:
                          id:
                            type: string
                            example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                          nom:
                            type: string
                            example: "Diabaté"
                          prenom:
                            type: string
                            example: "Dr Fatou"
                          email:
                            type: string
                            example: "dr.fatou@example.com"
                      certification:
                        type: object
                        properties:
                          fileId:
                            type: string
                            example: "file-uuid-54321"
                            description: "ID du fichier dans le service externe"
                          nom_fichier:
                            type: string
                            example: "ordre_medecins_ci.pdf"
                          taille:
                            type: integer
                            example: 1536000
                            description: "Taille en bytes"
                          mime_type:
                            type: string
                            example: "application/pdf"
                          description:
                            type: string
                            nullable: true
                            example: "Certificat d'inscription à l'Ordre des Médecins CI"
                          type_certification:
                            type: string
                            nullable: true
                            example: "ORDRE_MEDECINS"
                      statistiques:
                        type: object
                        properties:
                          totalCertifications:
                            type: integer
                            example: 2
                            description: "Nombre total de certifications après ajout"
                          nouvelleCertification:
                            type: boolean
                            example: true
                      upload:
                        type: object
                        properties:
                          uploadedBy:
                            type: string
                            example: "Admin Pierre Kouassi"
                          uploadedAt:
                            type: string
                            format: date-time
                            example: "2024-01-15T14:30:22.123Z"
                          ip:
                            type: string
                            example: "192.168.1.100"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-01-15T14:30:22.123Z"
              examples:
                premiere_certification:
                  summary: Première certification (Ordre des Médecins)
                  value:
                    success: true
                    message: "Certification uploadée avec succès"
                    data:
                      medecin:
                        id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                        nom: "Diabaté"
                        prenom: "Dr Fatou"
                        email: "dr.fatou@example.com"
                      certification:
                        fileId: "file-uuid-54321"
                        nom_fichier: "ordre_medecins_ci.pdf"
                        taille: 1536000
                        mime_type: "application/pdf"
                        description: "Certificat d'inscription à l'Ordre des Médecins CI"
                        type_certification: "ORDRE_MEDECINS"
                      statistiques:
                        totalCertifications: 1
                        nouvelleCertification: true
                      upload:
                        uploadedBy: "Admin Pierre Kouassi"
                        uploadedAt: "2024-01-15T14:30:22.123Z"
                        ip: "192.168.1.100"
                    timestamp: "2024-01-15T14:30:22.123Z"

                certification_supplementaire:
                  summary: Certification supplémentaire (Formation)
                  value:
                    success: true
                    message: "Certification uploadée avec succès"
                    data:
                      medecin:
                        id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                        nom: "Diabaté"
                        prenom: "Dr Fatou"
                        email: "dr.fatou@example.com"
                      certification:
                        fileId: "file-uuid-98765"
                        nom_fichier: "formation_continue_2024.pdf"
                        taille: 2048000
                        mime_type: "application/pdf"
                        description: "Attestation formation continue en cardiologie"
                        type_certification: "FORMATION_CONTINUE"
                      statistiques:
                        totalCertifications: 2
                        nouvelleCertification: true
                      upload:
                        uploadedBy: "Admin Pierre Kouassi"
                        uploadedAt: "2024-01-15T15:15:30.789Z"
                        ip: "192.168.1.100"
                    timestamp: "2024-01-15T15:15:30.789Z"

                sans_categorisation:
                  summary: Certification sans type spécifié
                  value:
                    success: true
                    message: "Certification uploadée avec succès"
                    data:
                      medecin:
                        id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                        nom: "Kouassi"
                        prenom: "Dr Jean"
                        email: "dr.jean@example.com"
                      certification:
                        fileId: "file-uuid-11111"
                        nom_fichier: "attestation_professionnelle.pdf"
                        taille: 1024000
                        mime_type: "application/pdf"
                        description: "Attestation professionnelle"
                        type_certification: null
                      statistiques:
                        totalCertifications: 1
                        nouvelleCertification: true
                      upload:
                        uploadedBy: "Admin Marie Traoré"
                        uploadedAt: "2024-01-15T16:00:45.123Z"
                        ip: "192.168.1.105"
                    timestamp: "2024-01-15T16:00:45.123Z"

        '400':
          description: Requête invalide
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                  message:
                    type: string
                  details:
                    type: object
              examples:
                no_file:
                  summary: Aucun fichier fourni
                  value:
                    success: false
                    error: "BAD_REQUEST"
                    message: "Aucun fichier certification fourni"
                    details:
                      code: "NO_FILE"
                      field: "certification"
                file_too_large:
                  summary: Fichier trop volumineux
                  value:
                    success: false
                    error: "BAD_REQUEST"
                    message: "Fichier trop volumineux. Maximum: 10MB"
                    details:
                      code: "FILE_TOO_LARGE"
                      maxSize: "10MB"
                invalid_format:
                  summary: Format de fichier non autorisé
                  value:
                    success: false
                    error: "BAD_REQUEST"
                    message: "Format de fichier non autorisé. Formats acceptés: PDF, JPG, PNG"
                invalid_status:
                  summary: Médecin pas en attente
                  value:
                    success: false
                    error: "BAD_REQUEST"
                    message: "Seuls les médecins en attente peuvent recevoir des documents"
                    details:
                      code: "INVALID_STATUS"
                      currentStatus: "VALIDE"

        '401':
          description: Non authentifié
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "UNAUTHORIZED"
                  message:
                    type: string
                    example: "Token d'authentification requis"

        '403':
          description: Accès refusé (rôle insuffisant)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "FORBIDDEN"
                  message:
                    type: string
                    example: "Accès réservé aux administrateurs"

        '404':
          description: Médecin non trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "NOT_FOUND"
                  message:
                    type: string
                    example: "Médecin non trouvé"
                  details:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "MEDECIN_NOT_FOUND"
                      medecinId:
                        type: string
                        example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"

        '500':
          description: Erreur serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                  message:
                    type: string
              examples:
                upload_service_error:
                  summary: Erreur service de fichiers
                  value:
                    success: false
                    error: "INTERNAL_ERROR"
                    message: "Erreur lors de l'upload du fichier"
                    details:
                      code: "UPLOAD_SERVICE_ERROR"
                general_error:
                  summary: Erreur générale
                  value:
                    success: false
                    error: "INTERNAL_ERROR"
                    message: "Erreur interne lors de l'upload de la certification"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT