openapi: 3.0.0
info:
  title: Admin Doctors Pending API
  description: Récupération simple des médecins en attente de validation
  version: 1.0.0

paths:
  /v1/admin/doctors/pending:
    get:
      tags:
        - Administration
      summary: Récupérer la liste des médecins en attente de validation
      description: |
        Endpoint simple pour consulter tous les médecins en attente de validation.
        
        **Fonctionnalités :**
        - 🟡 **Statut unique** : EN_ATTENTE seulement
        - 📄 **Pagination** : Contrôle page/limite
        - 📅 **Tri fixe** : Par date d'inscription (plus récent en premier)
        - ⚡ **Priorité** : Indication urgence si >48h
        
        **User Stories :** Administrateurs-US1 (Gestion comptes médecins)

      security:
        - bearerAuth: []
      
      parameters:
        - name: page
          in: query
          description: Numéro de page pour la pagination
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
            example: 1
        - name: limit
          in: query
          description: Nombre d'éléments par page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
            example: 20

      responses:
        '200':
          description: Liste des médecins en attente récupérée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Médecins en attente récupérés avec succès"
                  data:
                    type: object
                    properties:
                      medecins:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              example: "uuid-medecin-123"
                            userId:
                              type: string
                              example: "uuid-user-456"
                            medecinInfo:
                              type: object
                              properties:
                                nom:
                                  type: string
                                  example: "Diabaté"
                                prenom:
                                  type: string
                                  example: "Dr Fatou"
                                email:
                                  type: string
                                  example: "dr.fatou@example.com"
                                telephone:
                                  type: string
                                  example: "0107080910"
                                numeroOrdre:
                                  type: string
                                  example: "CI123456"
                                specialites:
                                  type: array
                                  items:
                                    type: string
                                  example: ["CARDIOLOGIE", "MEDECINE_GENERALE"]
                                experienceAnnees:
                                  type: integer
                                  example: 8
                                bio:
                                  type: string
                                  nullable: true
                                  example: "Cardiologue expérimenté..."
                                accepteDomicile:
                                  type: boolean
                                  example: false
                                accepteTeleconsultation:
                                  type: boolean
                                  example: false
                                accepteclinique:
                                  type: boolean
                                  example: true
                            validationDetails:
                              type: object
                              properties:
                                statutValidation:
                                  type: string
                                  example: "EN_ATTENTE"
                                dateInscription:
                                  type: string
                                  format: date-time
                                  example: "2024-01-15T10:30:00Z"
                                timeElapsed:
                                  type: string
                                  example: "36h"
                                isUrgent:
                                  type: boolean
                                  example: false
                                priority:
                                  type: string
                                  enum: [NORMALE, HAUTE]
                                  example: "NORMALE"
                            accountStatus:
                              type: object
                              properties:
                                statut:
                                  type: string
                                  example: "ACTIF"
                                isActive:
                                  type: boolean
                                  example: true
                                hasTokens:
                                  type: boolean
                                  example: false
                                  description: "Les médecins en attente n'ont pas de tokens"
                                canLogin:
                                  type: boolean
                                  example: false
                                  description: "Ne peuvent pas se connecter tant que non validés"
                      pagination:
                        type: object
                        properties:
                          currentPage:
                            type: integer
                            example: 1
                          totalPages:
                            type: integer
                            example: 3
                          totalCount:
                            type: integer
                            example: 45
                          limit:
                            type: integer
                            example: 20
                          hasNextPage:
                            type: boolean
                            example: true
                          hasPrevPage:
                            type: boolean
                            example: false
                          itemsOnPage:
                            type: integer
                            example: 20
                      statistics:
                        type: object
                        properties:
                          totalEnAttente:
                            type: integer
                            example: 45
                            description: "Nombre total de médecins en attente"
                      actions:
                        type: object
                        properties:
                          validateEndpoint:
                            type: string
                            example: "PUT /v1/admin/doctors/{id}/validate"
                      adminInfo:
                        type: object
                        properties:
                          reviewedBy:
                            type: string
                            example: "Admin Pierre"
                          reviewedAt:
                            type: string
                            format: date-time
                            example: "2024-01-15T14:30:00Z"
                          ip:
                            type: string
                            example: "192.168.1.100"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-01-15T14:30:22.123Z"
              examples:
                medecins_en_attente:
                  summary: Liste de médecins en attente
                  value:
                    success: true
                    message: "Médecins en attente récupérés avec succès"
                    data:
                      medecins: 
                        - id: "uuid-medecin-123"
                          userId: "uuid-user-456"
                          medecinInfo:
                            nom: "Diabaté"
                            prenom: "Dr Fatou"
                            email: "dr.fatou@example.com"
                            telephone: "0107080910"
                            numeroOrdre: "CI123456"
                            specialites: ["CARDIOLOGIE"]
                            experienceAnnees: 8
                            bio: "Cardiologue expérimenté..."
                            accepteDomicile: false
                            accepteTeleconsultation: false
                            accepteclinique: true
                          validationDetails:
                            statutValidation: "EN_ATTENTE"
                            dateInscription: "2024-01-15T10:30:00Z"
                            timeElapsed: "36h"
                            isUrgent: false
                            priority: "NORMALE"
                          accountStatus:
                            statut: "ACTIF"
                            isActive: true
                            hasTokens: false
                            canLogin: false
                        - id: "uuid-medecin-789"
                          userId: "uuid-user-012"
                          medecinInfo:
                            nom: "Kouassi"
                            prenom: "Dr Jean"
                            email: "dr.jean@example.com"
                            telephone: "0109080706"
                            numeroOrdre: "CI789012"
                            specialites: ["PEDIATRIE"]
                            experienceAnnees: 5
                            bio: null
                            accepteDomicile: true
                            accepteTeleconsultation: true
                            accepteclinique: true
                          validationDetails:
                            statutValidation: "EN_ATTENTE"
                            dateInscription: "2024-01-10T08:15:00Z"
                            timeElapsed: "120h"
                            isUrgent: true
                            priority: "HAUTE"
                          accountStatus:
                            statut: "ACTIF"
                            isActive: true
                            hasTokens: false
                            canLogin: false
                      pagination:
                        currentPage: 1
                        totalPages: 3
                        totalCount: 45
                        limit: 20
                        hasNextPage: true
                        hasPrevPage: false
                        itemsOnPage: 20
                      statistics:
                        totalEnAttente: 45
                      actions:
                        validateEndpoint: "PUT /v1/admin/doctors/{id}/validate"
                      adminInfo:
                        reviewedBy: "Admin Pierre"
                        reviewedAt: "2024-01-15T14:30:00Z"
                        ip: "192.168.1.100"
                    timestamp: "2024-01-15T14:30:22.123Z"

                liste_vide:
                  summary: Aucun médecin en attente
                  value:
                    success: true
                    message: "Médecins en attente récupérés avec succès"
                    data:
                      medecins: []
                      pagination:
                        currentPage: 1
                        totalPages: 0
                        totalCount: 0
                        limit: 20
                        hasNextPage: false
                        hasPrevPage: false
                        itemsOnPage: 0
                      statistics:
                        totalEnAttente: 0
                      actions:
                        validateEndpoint: "PUT /v1/admin/doctors/{id}/validate"
                      adminInfo:
                        reviewedBy: "Admin Pierre"
                        reviewedAt: "2024-01-15T14:30:00Z"
                        ip: "192.168.1.100"
                    timestamp: "2024-01-15T14:30:22.123Z"

        '401':
          description: Non authentifié
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "UNAUTHORIZED"
                  message:
                    type: string
                    example: "Token d'authentification requis"

        '403':
          description: Accès refusé (rôle insuffisant)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "FORBIDDEN"
                  message:
                    type: string
                    example: "Accès réservé aux administrateurs"

        '400':
          description: Paramètres de pagination invalides
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "VALIDATION_ERROR"
                  message:
                    type: string
                    example: "Paramètres de pagination invalides"
                  details:
                    type: object
                    example:
                      page: "Doit être un nombre entier positif"
                      limit: "Doit être entre 1 et 100"

        '500':
          description: Erreur serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "INTERNAL_ERROR"
                  message:
                    type: string
                    example: "Erreur interne lors de la récupération des médecins en attente"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT