openapi: 3.0.0
paths:
  /v1/medecins/validation-status:
    get:
      tags:
        - Médecins
      summary: Consultation du statut de validation médecin
      description: |
        Récupère le statut de validation détaillé d'un médecin avec :
        - Statut actuel (EN_ATTENTE, VALIDE, REJETE)
        - Temps écoulé depuis la demande
        - Actions recommandées selon le statut
        - Informations de contact pour assistance
        - Détails de rejet si applicable
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Statut de validation récupéré avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Statut de validation récupéré"
                  data:
                    $ref: '#/components/schemas/ValidationStatusResponse'
                  timestamp:
                    type: string
                    format: date-time
                    example: "2024-01-15T14:30:22.123Z"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          description: Accès refusé - Rôle médecin requis
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: "ACCESS_DENIED"
                message: "Accès réservé aux médecins"
        '404':
          description: Profil médecin non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                error: "MEDECIN_PROFILE_NOT_FOUND"
                message: "Profil médecin non trouvé"
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    ValidationStatusResponse:
      type: object
      description: Réponse complète du statut de validation
      properties:
        validationStatus:
          type: object
          properties:
            current:
              $ref: '#/components/schemas/StatutValidationMedecin'
            dateValidation:
              type: string
              format: date
              nullable: true
              example: "2024-01-15"
              description: "Date de validation si statut VALIDE"
            motifRejet:
              type: string
              nullable: true
              example: "Documents illisibles, veuillez fournir des copies plus claires"
              description: "Motif de rejet si statut REJETE"
            timeElapsed:
              type: string
              example: "48h"
              description: "Temps écoulé depuis la demande"
            estimatedTime:
              type: string
              nullable: true
              example: "Validation en cours, sous 48h"
              description: "Temps estimé restant pour validation"
            statusInfo:
              type: object
              properties:
                message:
                  type: string
                  example: "Votre compte médecin est en cours de validation par notre équipe administrative."
                description:
                  type: string
                  example: "Nous vérifions actuellement vos documents et informations professionnelles."
                priority:
                  type: string
                  enum: [NORMALE, VALIDÉ, URGENT]
                  example: "NORMALE"
                canPractice:
                  type: boolean
                  example: false
                  description: "Le médecin peut-il exercer sur la plateforme"
        medecinInfo:
          type: object
          properties:
            id:
              type: string
              format: uuid
              example: "123e4567-e89b-12d3-a456-426614174000"
            numeroOrdre:
              type: string
              example: "CI-MED-12345"
            specialites:
              type: array
              items:
                $ref: '#/components/schemas/SpecialiteMedicale'
              example: ["CARDIOLOGIE", "MEDECINE_INTERNE"]
            bio:
              type: string
              nullable: true
              example: "Cardiologue avec 15 ans d'expérience"
            experienceAnnees:
              type: integer
              nullable: true
              example: 15
        validationDetails:
          type: object
          properties:
            nextSteps:
              type: array
              items:
                type: string
              example: [
                "Patientez pendant la validation de votre dossier",
                "Vérifiez que tous vos documents sont bien lisibles",
                "Vous recevrez un email de confirmation une fois validé"
              ]
            documentsRequired:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                    example: "Diplôme de médecine"
                  description:
                    type: string
                    example: "Copie certifiée conforme du diplôme"
                  required:
                    type: boolean
                    example: true
            contactInfo:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "validation@medecins-patients.ci"
                telephone:
                  type: string
                  example: "+225 XX XX XX XX"
                horaires:
                  type: string
                  example: "Lundi-Vendredi 8h-17h"
            validatedBy:
              type: object
              nullable: true
              description: "Informations de l'admin qui a validé (si VALIDE)"
              properties:
                nom:
                  type: string
                  example: "KOUAME"
                prenom:
                  type: string
                  example: "Marie"
                email:
                  type: string
                  format: email
                  example: "marie.kouame@admin.ci"
        rejectionDetails:
          type: object
          nullable: true
          description: "Détails du rejet (si REJETE)"
          properties:
            motif:
              type: string
              example: "Documents illisibles"
            actions:
              type: array
              items:
                type: string
              example: [
                "Corriger les documents mentionnés",
                "Contacter l'équipe de validation",
                "Resoummettre le dossier complet"
              ]
            urgency:
              type: string
              enum: [BASSE, NORMALE, HAUTE]
              example: "HAUTE"
        waitingDetails:
          type: object
          nullable: true
          description: "Détails de l'attente (si EN_ATTENTE)"
          properties:
            queuePosition:
              type: string
              example: "Information non disponible"
            averageProcessingTime:
              type: string
              example: "24-48 heures"
            workingDays:
              type: string
              example: "Lundi-Vendredi"
            holidays:
              type: string
              example: "Traitement suspendu les weekends et jours fériés"
      required:
        - validationStatus
        - medecinInfo
        - validationDetails